### ISSUE TITLE
Switching state not ordered

### ISSUE THREAD

**Issue by kozlovic** [nats-io/graft#11]
When a node switches state, it invokes `go n.handler.StateChange(old, state)` in `switchState`, this is wrong since it does not guarantees the order of the state changes. If in time a node goes from FOLLOWER to CANDIDATE and then CANDIDATE to LEADER, the state change channel may end-up having the two state changes reversed due to the execution of a go routine to report the change of the state.

**Comment by ColinSullivan1** [comment]
Agreed here.

**Comment by derekcollison** [comment]
Do we have a test that proves this?

**Comment by kozlovic** [comment]
Yes, on Travis, for code coverage (without -race), `TestStateChangeHandler` often fails when state is expected to go from FOLLOWER to CANDIDATE: it gets instead CANDIDATE to Leader.
I am about to propose a fix.

**Comment by kozlovic** [comment]
Also, if you were to replace `go n.handler.StateChange(old, state)` with:
```
go func() {
    time.Sleep(time.Duration(mrand.Int31n(10)) * time.Millisecond)
    n.handler.StateChange(old, state)
}()
```
you would get the failure pretty often. My guess is that It used to work ok when you had `GOMAXPROCS=1` which was removed recently.

**Comment by derekcollison** [comment]
ok so state change mutex?

**Comment by kozlovic** [comment]
No, that would not help. The issue is that the state change (or error) is invoked from a go routine. Execution of go routine is not under your control. So `go StateChange(FOLLOWER, CANDIDATE)` followed by `go StateChange(CANDIDATE, LEADER)` could result in reverse execution. Locking in StateChange handler would not help.
About to submit PR for review.
