### ISSUE TITLE
Handle updating configuration

### ISSUE THREAD

**Issue by derekcollison** [nats-io/graft#2]
The RAFT protocol defines how to handle configuration changes, we need to implement.

**Comment by jmealo** [comment]
@derekcollison: Any updates on fully implementing the protocol?

**Comment by derekcollison** [comment]
Added in @tylertreat

**Comment by tylertreat** [comment]
No immediate plans. We're currently using Hashicorp's [Raft library](https://github.com/hashicorp/raft) in conjunction with a [NATS-based transport](https://github.com/nats-io/nats-on-a-log) for NATS Streaming clustering. That library already supports configuration changes to the cluster by threading them through Raft, and it's just generally a mature Raft implementation (used by Consul, etc.).
