### ISSUE TITLE
NATS v1.10.0 - Cluster never elects a leader

### ISSUE THREAD

**Issue by basgys** [nats-io/graft#22]
graft currently uses nats `v1.9.2`, but when it is included in a project that uses NATS `v1.10.0`, the cluster never elects a leader.

All members get stuck as candiates in the leader election process. 

**Steps to reproduce**

1. `git clone git@github.com:nats-io/graft.git`
2. `go get github.com/nats-io/nats.go@latest` (v1.10.0)
3. `go test ./...`

**Expected result**

```
ok  	github.com/nats-io/graft	Xs
?   	github.com/nats-io/graft/pb	[no test files]
```

**Actual result**

```
--- FAIL: TestNatsLeaderElection (1.13s)
    test_helper.go:51: Cluster doesn't match expect state: expected 1 leaders, 4 followers, 0 candidates, actual 0 Leaders, 0 followers, 5 candidates

        1 - github.com/deixis/graft/test_helper.go:124
        2 - github.com/deixis/graft/nats_rpc_test.go:62
        3 - ...
FAIL
FAIL	github.com/nats-io/graft	Xs
?   	github.com/nats-io/graft/pb	[no test files]
FAIL
```

I am not sure whether that is a graft, a NATS problem, or if you even consider it as an issue.

**Comment by derekcollison** [comment]
Thanks will take a look.

**Comment by derekcollison** [comment]
I suspect a protocol buffer problem TBH. Looking now.

**Comment by derekcollison** [comment]
ok should be resolved.

**Comment by basgys** [comment]
@derekcollison I confirm that everything works now. Thanks for your prompt answer and fix! 🙏 🙌
